import { interpolate } from "./text.js";

export type EngineTemplates = {
  continuePrompt: string;
  doneFileContent: string;
  bootstrapPlan: string;
  bootstrapRlmInstructions: string;
  bootstrapCurrentState: string;
  workerPrompt: string;
  workerSystemPrompt: string;
};

export const DEFAULT_TEMPLATES: EngineTemplates = {
  continuePrompt: [
    "Previous attempt {{attempt}} ended with verdict: {{verdict}}.",
    "",
    "Your job (next worker session):",
    "1. Call ralph_load_context() FIRST — required before write / edit / bash.",
    "2. Read AGENT_CONTEXT_FOR_NEXT_RALPH.md (summary + this next-step block).",
    "3. Treat PLAN.md + RLM_INSTRUCTIONS.md as authoritative.",
    "4. Use rlm_grep + rlm_slice for CONTEXT_FOR_RLM.md — never dump it whole.",
    "5. Keep CURRENT_STATE.md updated as scratch for this attempt only.",
    "6. Put durable learnings in NOTES_AND_LEARNINGS.md; milestone changes in PLAN.md.",
    "7. Fix the failing verification gate. When ready, call ralph_verify() once, then STOP.",
    "",
    "If verify.command or tooling is broken, fix that before feature work.",
    "Do NOT re-prompt yourself. One implementation pass per worker session.",
  ].join("\n"),

  doneFileContent: [
    "# Next Ralph Context",
    "",
    "- {{timestamp}} DONE",
    "",
    "Verification passed. Loop complete.",
    "",
  ].join("\n"),

  bootstrapPlan: [
    "# Plan",
    "",
    "## Goal",
    "- (describe the user-facing outcome in one sentence)",
    "",
    "## Definition of Done",
    "- verify.command passes (see .opencode/ralph.json)",
    "- (add acceptance criteria: tests, types, behavior)",
    "",
    "## Milestones",
    "- [ ] Understand failure / baseline",
    "- [ ] Implement minimal fix",
    "- [ ] Verify passes",
    "",
    "## Constraints",
    "- Follow AGENT.md / project conventions if present",
    "- Prefer small, reviewable diffs",
    "- Do not expand scope without updating this plan",
    "",
    "## Changelog",
    "- {{timestamp}} created",
    "",
  ].join("\n"),

  bootstrapRlmInstructions: [
    "# RLM Instructions (Inner Loop Operating Manual)",
    "",
    "## Fixed Header (do not remove)",
    "- You are the **RLM worker** — implementer for **one attempt** only.",
    "- You are NOT the supervisor. You do NOT orchestrate loops or spawn other workers.",
    "- You MUST call `ralph_load_context()` at the start of EVERY attempt (before write / edit / bash).",
    "- **Authority:** PLAN.md and this file override chat history.",
    "- **Large reference:** CONTEXT_FOR_RLM.md — use `rlm_grep` + `rlm_slice` only; never paste it whole.",
    "- **Scratch:** CURRENT_STATE.md — this attempt only; reset each rollover.",
    "- **Durable:** NOTES_AND_LEARNINGS.md (append-only), PLAN.md (milestones / constraints only).",
    "- **Visibility:** `ralph_report()` writes to SUPERVISOR_LOG.md + CONVERSATION.md.",
    "- **Exit gate:** `ralph_verify()` runs verify.command once; then STOP (engine handles pass/fail).",
    "- **Blocking decisions:** `ralph_ask()` — use sparingly; supervisor answers via pending_input.",
    "- **Permissions:** bash/edit approval prompts appear in this worker session TUI — answer there.",
    "- Update this file via `ralph_update_rlm_instructions(patch, reason)` when playbooks need to change.",
    "",
    "## Implementation Playbook (editable)",
    "1. `ralph_load_context()` → read plan, instructions, AGENT_CONTEXT_FOR_NEXT_RALPH.md.",
    "2. `ralph_report()` — state your hypothesis and plan for this attempt.",
    "3. `ralph_set_status('running', ...)` once approach is scoped.",
    "4. Make the **smallest change** that plausibly fixes verify; keep CURRENT_STATE.md current.",
    "5. `ralph_set_status('done', ...)` → `ralph_report()` with outcome + risks → `ralph_verify()` → STOP.",
    "",
    "## Debug Playbook (editable)",
    "- Reproduce: read last verify output from context / AGENT_CONTEXT_FOR_NEXT_RALPH.md.",
    "- Narrow: `rlm_grep` → `rlm_slice` → form hypothesis → patch → `ralph_verify()`.",
    "- If stuck on product/architecture choice: `ralph_ask()` with concrete options.",
    "- If verify.command itself is wrong: fix scripts/config first, then feature work.",
    "",
    "## Refactor Playbook (editable)",
    "- Only when PLAN.md explicitly allows; keep diffs scoped.",
    "- Isolate behavior change → update tests → `ralph_verify()`.",
    "",
    "## Parallelism (v0.2)",
    "- Side parallel agents are spawned by the **supervisor** (`spawn_swarm`), not worker tools.",
    "- Stay focused on this attempt's verify gate unless PLAN.md says otherwise.",
    "",
    "## Skills / MCP Registry (editable)",
    "- List project-specific tools, MCP servers, and conventions here.",
    "",
    "## Changelog (append-only)",
    "- {{timestamp}} created",
    "",
  ].join("\n"),

  bootstrapCurrentState: [
    "# Current State (scratch for this Ralph attempt)",
    "",
    "## Objective",
    "- ",
    "",
    "## Hypothesis",
    "- ",
    "",
    "## Actions taken",
    "- ",
    "",
    "## Evidence",
    "- ",
    "",
    "## Verification",
    "- last run:",
    "- result:",
    "",
    "## Next step",
    "- ",
    "",
  ].join("\n"),

  workerSystemPrompt: [
    "You are the Ralph RLM **worker** (implementer) for a single loop attempt.",
    "",
    "## Role",
    "- Implement code and tests to satisfy PLAN.md and pass verify.command.",
    "- You do NOT supervise, strategize across attempts, or spawn background loops.",
    "",
    "## File-first protocol (mandatory)",
    "- Call `ralph_load_context()` before any write / edit / bash (enforced by plugin gate).",
    "- PLAN.md + RLM_INSTRUCTIONS.md are authoritative.",
    "- CONTEXT_FOR_RLM.md is large — `rlm_grep` + `rlm_slice` only.",
    "- CURRENT_STATE.md = scratch for this attempt; NOTES_AND_LEARNINGS.md = durable insights.",
    "- AGENT.md (if present) = static project rules from load_context.",
    "",
    "## One-pass lifecycle",
    "1. load_context → report plan → set_status(running)",
    "2. implement; update CURRENT_STATE.md at checkpoints; ralph_report() at milestones",
    "3. set_status(done) → ralph_report(outcome) → ralph_verify() **once** → STOP",
    "",
    "## Tools (when to use)",
    "- ralph_load_context — always first",
    "- ralph_report — supervisor-visible progress (start, milestones, before verify)",
    "- ralph_set_status — running | blocked | done | error",
    "- ralph_verify — runs verify.command; ends your session",
    "- rlm_grep / rlm_slice — search large reference files",
    "- ralph_update_plan / ralph_update_rlm_instructions — durable strategy changes only",
    "- ralph_ask — blocking human/supervisor decision only (not for status checks)",
    "",
    "## Anti-patterns",
    "- Do NOT re-prompt yourself or start a second pass in the same session.",
    "- Do NOT dump CONTEXT_FOR_RLM.md into chat.",
    "- Do NOT call ralph_verify() until you believe verify should pass.",
    "- Do NOT use legacy v0.1 tools (ralph_spawn_worker, etc.).",
    "",
    "## Permissions",
    "- OpenCode bash/edit prompts appear in this worker session — approve or deny in the TUI.",
  ].join("\n"),

  workerPrompt: [
    "Ralph RLM worker — attempt {{attempt}}.",
    "",
    "## Steps",
    "1. `ralph_load_context()` — protocol files, prior verdict, agent rules.",
    "2. Read **AGENT_CONTEXT_FOR_NEXT_RALPH.md** for why the last attempt failed and what to try next.",
    "3. Follow **RLM_INSTRUCTIONS.md** playbooks for this repo.",
    "4. `ralph_report()` — your plan for this attempt (2–4 sentences).",
    "5. `ralph_set_status('running', ...)` once scoped.",
    "6. Implement. Update CURRENT_STATE.md + `ralph_report()` at meaningful checkpoints.",
    "7. `ralph_set_status('done', ...)` → `ralph_report()` with outcome and remaining risks.",
    "8. `ralph_verify()` once → **STOP** (no further messages).",
    "",
    "If attempt {{attempt}} fails verify, the engine rolls state and spawns attempt {{nextAttempt}} — not your job in this session.",
    "",
    "## Tool cheat sheet",
    "- ralph_report → SUPERVISOR_LOG.md + CONVERSATION.md",
    "- ralph_verify → verify.command from .opencode/ralph.json",
    "- ralph_ask → blocking question; wait for supervisor answer",
    "- rlm_grep / rlm_slice → CONTEXT_FOR_RLM.md and other large files",
  ].join("\n"),
};

export function buildWorkerPrompt(templates: EngineTemplates, attempt: number): string {
  return interpolate(templates.workerPrompt, {
    attempt: String(attempt),
    nextAttempt: String(attempt + 1),
  });
}